#!/bin/bash
# Ubuntu automated installer script, this is a simple script to help
# you get the right setup for your server enviroment.
# this script is build upon serval diffrent guides form all aorund
# the interne. as for now its in development mode and should not be used
# for any kinda setup. so fare i got whiptail running for the most of it
# updates will follow..
#
#
# Author: Nickless - Admin@isengard.dk
#-------------------------------------------------------------------------
# define script path
Core_path="Core"
ISPConfig_path="ISPConfig"
Extras_path="Extras"

# Ensure we enter correct folder before running script
# we dont use this in development mode.
if [ -f /opt/server-setup/server-setup ]; then
   cd /opt/server-setup
   if [ -f reboot.tmp ]; then
     echo "your system need to reboot, before script can continue."
     echo "if you know what your doing then: rm /opt/server-setup/reboot.tmp"
     echo "and run script again."
     exit 0
  fi
fi

# Load config values created on first run.
if [ -f /etc/server-setup.conf ]; then
   echo "Found config in /etc/server-setup.conf"
else
   echo "We are unable to locate config file."
   sleep 0.5
   echo "Installing config.."
   ln -s /opt/server-setup/config.sh /etc/server-setup.conf
   if [ -f /etc/server-setup.conf ]; then
      echo "New config file have been added."
      echo "please see /etc/server-setup.conf for more info."
   fi
fi

# load config values before the rest of the script.
source config.sh

# check for appending commands.
# like --help or --run-upgrade / --run-uninstall
ARGS=$1

# Basicly we load the core here.
# its pretty simple script whit afew
# along whit the hole menu system.
for file in $Core_path/*.sh; do
   source $file
done

# We need to call lsb_release to get current Distro infomartion
# to ensure we call the right script when installing ISPConfig 3
# this way we can ensure everybody can call the script.
. /etc/lsb-release

# this will need a distro check to
# to ensure we use the Correct version to enable ispconfig.
# or maybe make it as an option selected when installing ispconfig
for file in $ISPConfig_path/*.$DISTRIB_RELEASE.sh; do
   source $file
done

# load Extra's - various scripts that
# can help a newbie install diffrent things
# like OpenVPN / Munin&Monit / Mumble / Gitlab
# and so on..
for file in $Extras_path/*.sh; do
   source $file
done

# is root present ?
# if not kill script ?
CheckRoot

# determin webserver for some scripts
check_webserver

# Start Menu System
clear
Collect_info
clear
EnableQuestions
while [ opt != '' ]
    do
    if [[ $opt = "" ]]; then 
            exit;
    else
        case $opt in
        1) clear;
        option_picked "Detecting hostname, please standby.";
        sleep 0.5
        # need new way to check and sed new info
        clear;
        EnableQuestions;
        ;;

        2) clear;
            option_picked "Setting up root account, please standby.";
            sleep 0.5
            AllowRootSSH
        clear;
        EnableQuestions;
            ;;

        3) clear;
           option_picked "Preparing server, please standby.";
           # ISPConfig 3 START
               SetupBasic
               DisableApparmor
               EnableMYSQL
               EnableDovecot
               EnableApache
               EnableVirus
               EnableMailman
               EnablePureFTPD
               EnableQuota
               EnableBind
               EnableStats
               EnableJailkit
               EnableFail2ban
               EnableFail2BanRulesDovecot
               EnableISPConfig3
             echo -e "${MENU} Install Squirrelmail Webmail?${NORMAL}"
             read -p "(y/n) " squirrel
             if [ $squirrel = "y" ]; then
                EnableSquirrelmail
             fi
             echo -e "${MENU} Install RoundCube Webmail?${NORMAL}"
             read -p "(y/n) " roundcube
             if [ $roundcube = "y" ]; then
                EnableRoundcube
             fi
             echo -e "${MENU} Install ISPC Clean Theme for ispconfig?${NORMAL}"
             read -p "(y/n) " theme
             if [ $theme = "y" ]; then
                EnableISPC_Clean
             fi
           # ISPConfig 3 END
        clear
        EnableQuestions;
        ;;

        4) clear;
            option_picked "Enabling Extra's..";
            EnableExtras;
            clear;
            EnableQuestions;
            ;;

        5)
        clear;
            echo -e "${MENU} Comming soon..${NORMAL}"
            echo -e "${MENU} for more info see https://github.com/gimli/server-setup ${NORMAL}"
            echo -e "${MENU} This will return to the main menu in 10 sec. ${NORMAL}"
            echo ""
            echo -e "${MENU} press any key to return to main menu..${NORMAL}"
            read DUMMY
        clear;
        EnableQuestions;
        ;;
        x)exit;
        ;;

        \n)exit;
        ;;

        *)clear;
        EnableQuestions;
        ;;
    esac
fi
done
