#!/bin/bash
# Ubuntu automated installer script, this is a simple script to help
# you get the right setup for your server enviroment.
# this script is build upon serval diffrent guides form all aorund
# the interne. as for now its in development mode and should not be used
# for any kinda setup. so fare i got whiptail running for the most of it
# updates will follow..
#
#
# Author: Nickless - Admin@isengard.dk
#-------------------------------------------------------------------------
# define script path
Core_path="Core"
ISPConfig_path="ISPConfig"
Extras_path="Extras"

# Ensure we enter correct folder before running script
# we dont use this in development mode.
if [ -f /opt/server-setup/server-setup ]; then
   cd /opt/server-setup
   if [ -f reboot.tmp ]; then
     echo "your system need to reboot, before script can continue."
     echo "if you know what your doing then: rm /opt/server-setup/reboot.tmp"
     echo "and run script again."
     exit 0
  fi
fi

# Load config values created on first run.
if [ -f /etc/server-setup.conf ]; then
   echo "Found config in /etc/server-setup.conf"
else
   echo "We are unable to locate config file."
   sleep 0.5
   echo "Installing config.."
   ln -s /opt/server-setup/config.sh /etc/server-setup.conf
   if [ -f /etc/server-setup.conf ]; then
      echo "New config file have been added."
      echo "please see /etc/server-setup.conf for more info."
   fi
fi

# load config values before the rest of the script.
source config.sh

# check for appending commands.
# like --help or --run-upgrade / --run-uninstall
ARGS=$1

# Basicly we load the core here.
# its pretty simple script whit afew
# along whit the hole menu system.
for file in $Core_path/*.sh; do
   source $file
done

# We need to call lsb_release to get current Distro infomartion
# to ensure we call the right script when installing ISPConfig 3
# this way we can ensure everybody can call the script.
. /etc/lsb-release

# this will need a distro check to
# to ensure we use the Correct version to enable ispconfig.
# or maybe make it as an option selected when installing ispconfig
for file in $ISPConfig_path/*.$DISTRIB_RELEASE.sh; do
   source $file
done

# load Extra's - various scripts that
# can help a newbie install diffrent things
# like OpenVPN / Munin&Monit / Mumble / Gitlab
# and so on..
for file in $Extras_path/*.sh; do
   source $file
done

# is root present ?
# if not kill script ?
CheckRoot

# Start Menu System
EnableQuestions
